#!/usr/bin/env python3
"""Manuscript consistency checker for the QTA report.

Fails (exit 1) if the manuscript disagrees with the canonical generated outputs or
contains forbidden / unprofessional / contradictory language. Source of truth for
gate counts is ``results_gate_table.csv`` (generated by ``qta_full_sim.py``).

Checks:
  1. manuscript gate-count summaries agree with results_gate_table.csv
  2. superseded tau_c = 27.7 us never appears without 'SUPERSEDED'
  3. no PASS asserted from weak evidence (ASSUMED/DESIGN_SPECIFIED/MANUFACTURER_SPEC/
     LITERATURE_BOUND/UNKNOWN/NOT_INSTALLED)
  4. forbidden phrases ('3D implemented', 'COMSOL', 'validated hardware',
     affirmative simultaneous LCVD+sensing)
  5. Mode B and Mode D laser vectors are not mixed
  6. page-number leakage patterns in extracted manuscript text (if PDF readable)
  7. unprofessional wording ('serious 1D/2D', etc.) and bullet artifacts
"""
from __future__ import annotations

import csv
import re
import subprocess
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEX = ROOT / "qta_manuscript_v4.tex"
PDF = ROOT / "qta_manuscript_v4.pdf"
GATE_CSV = ROOT / "results_gate_table.csv"

FAILURES: list = []
def fail(check: str, detail: str) -> None:
    FAILURES.append((check, detail))
    print(f"  [FAIL] {check}\n         {detail}")
def ok(check: str) -> None:
    print(f"  [ok]   {check}")


def canonical_counts() -> dict:
    rows = list(csv.DictReader(open(GATE_CSV, encoding="utf-8")))
    c = Counter(r["status"] for r in rows)
    return {"total": len(rows), "PASS": c.get("PASS", 0), "FAIL": c.get("FAIL", 0),
            "CONDITIONAL": c.get("CONDITIONAL", 0), "BLOCKED": c.get("BLOCKED", 0),
            "UNKNOWN": c.get("UNKNOWN", 0), "DERIVED_CHECK": c.get("DERIVED_CHECK", 0)}


def main() -> int:
    tex = TEX.read_text(encoding="utf-8")
    canon = canonical_counts()
    print("=" * 70)
    print("MANUSCRIPT CONSISTENCY CHECK")
    print("=" * 70)
    print(f"Canonical (results_gate_table.csv): {canon}\n")

    # ---- 1. gate-count summaries agree with the CSV ----
    # any cluster mentioning conditional+blocked counts is a summary; the FULL
    # summary must equal canonical. A known-stale tuple must never appear.
    def macro_count(macro: str) -> list:
        return [int(n) for n in re.findall(r"(\d+)~\\" + macro + r"\b", tex)]
    cond = set(macro_count("conditional")); blok = set(macro_count("blocked"))
    der = set(macro_count("derivedcheck"))
    # canonical numbers must be present
    if canon["CONDITIONAL"] in cond and canon["BLOCKED"] in blok and canon["DERIVED_CHECK"] in der:
        ok(f"canonical summary present ({canon['CONDITIONAL']} cond / {canon['BLOCKED']} blocked / {canon['DERIVED_CHECK']} derived)")
    else:
        fail("canonical gate summary present in manuscript",
             f"expected cond={canon['CONDITIONAL']} blocked={canon['BLOCKED']} derived={canon['DERIVED_CHECK']}; "
             f"found cond={sorted(cond)} blocked={sorted(blok)} derived={sorted(der)}")
    # stale/contradictory totals: any conditional count that is neither canonical
    # nor a plausibly-labelled subset is flagged. We hard-fail on the known stale
    # values and on any 'N total gates' != canonical total.
    for n in cond:
        if n != canon["CONDITIONAL"] and n in (39,):
            fail("no stale CONDITIONAL count", f"found {n} (canonical {canon['CONDITIONAL']})")
    for n in blok:
        if n != canon["BLOCKED"] and n in (21,):
            fail("no stale BLOCKED count", f"found {n} (canonical {canon['BLOCKED']})")
    for tot in re.findall(r"(\d+)\s+total gates", tex):
        if int(tot) != canon["total"]:
            fail("'N total gates' equals canonical total", f"found {tot} != {canon['total']}")
    if not any(f[0].startswith("no stale") or "total gates" in f[0] for f in FAILURES):
        ok(f"no stale/contradictory gate totals (canonical total = {canon['total']})")

    # ---- 2. superseded tau_c 27.7 must carry SUPERSEDED ----
    bad277 = []
    for m in re.finditer(r"27\.7", tex):
        window = tex[max(0, m.start() - 200): m.end() + 200].lower()
        if "supersed" not in window:
            bad277.append(m.start())
    if bad277:
        fail("tau_c=27.7us always marked SUPERSEDED", f"{len(bad277)} unmarked occurrence(s)")
    else:
        ok("superseded tau_c=27.7us always labelled SUPERSEDED")

    # ---- 3. no PASS from weak evidence ----
    weak = ["assumed", "designspec", "mfrspec", "litbound", "notinstalled"]  # evidence axis only
    pass_bad = []
    for ln in tex.splitlines():
        low = ln.lower()
        if "$|$" in ln or "0~\\textsc{pass}" in low:   # gate-count summary / zero-pass rows
            continue
        if re.search(r"\\textsc\{pass\}", low) and any("\\" + w in low for w in weak):
            if not any(k in low for k in ("no gate", "not ", "only after", "allowed only",
                                          "absolute rule", "requires", "before", "item[")):
                pass_bad.append(ln.strip()[:80])
    if pass_bad:
        fail("no PASS asserted from weak evidence", f"{pass_bad[:2]}")
    else:
        ok("no PASS asserted from ASSUMED/DESIGN_SPECIFIED/etc. evidence")

    # ---- 4. forbidden phrases (negation-aware) ----
    forbidden = {
        r"validated\s+3d\s+hardware": "claims validated 3D hardware",
        r"\bcomsol\b": "mentions COMSOL",
        r"validated\s+hardware": "claims validated hardware",
    }
    fb = []
    for pat, msg in forbidden.items():
        for m in re.finditer(pat, tex, re.I):
            w = tex[max(0, m.start() - 70): m.end() + 20].lower()
            if not any(k in w for k in ("no ", "not ", "without", "neither", "never")):
                fb.append(msg)
                break
    for m in re.finditer(r"simultaneous", tex, re.I):
        w = tex[max(0, m.start() - 130): m.end() + 130].lower()
        if ("lcvd" in w or "sensing" in w) and not any(
                k in w for k in ("not ", "never", "mutually exclusive", "no ", "are not")):
            fb.append("affirmative simultaneous LCVD+sensing")
            break
    if fb:
        fail("no forbidden phrases (3D/COMSOL/validated-hardware/simultaneous)", f"{fb}")
    else:
        ok("no forbidden phrases (3D implemented, COMSOL, validated hardware, simultaneous LCVD+sensing)")

    # ---- 5. Mode B / Mode D laser vectors not mixed ----
    # Real mixing = a specific Mode-B fs LASER VALUE inside a Mode-D readout / D6 / D7
    # gate line (or vice versa). Section/subsection titles and explicitly-"separate"
    # lines are not mixing. Confirm the separation marker exists.
    sep_marker = bool(re.search(r"separate from Mode~?D NV readout|Mode~?B LCVD optics", tex))
    mix = []
    for ln in tex.splitlines():
        low = ln.lower().strip()
        if low.startswith("\\section") or low.startswith("\\subsection") or "separate" in low:
            continue
        modeb_val = bool(re.search(r"100\\,fs|10\\,fj|361\\,nm|1\\,mhz|\^a\b", low))
        moded_gate = bool(re.search(r"\bd6\b|\bd7\b|nv readout", low))
        if modeb_val and moded_gate:
            mix.append(ln.strip()[:80])
    if mix:
        fail("Mode B and Mode D laser vectors not mixed", f"{mix[:2]}")
    elif not sep_marker:
        fail("Mode B / Mode D laser separation marker present", "no explicit separation statement found")
    else:
        ok("Mode B (fs LCVD) and Mode D (NV readout) laser vectors kept separate")

    # ---- 6. page-number leakage in extracted PDF text (same-line only) ----
    if PDF.exists():
        try:
            txt = subprocess.run(["pdftotext", str(PDF), "-"], capture_output=True,
                                 text=True, timeout=60).stdout
            leaks = []
            # a page number glued to a heading word ON THE SAME LINE (horizontal ws)
            for pat in [r"(?m)^[ \t]*\d{1,3}[ \t]+Gate counts",
                        r"(?m)^[ \t]*\d{1,3}[ \t]+Mode Label",
                        r"(?m)^[ \t]*\d{1,3}[ \t]+\d{1,3}[ \t]+Committed",
                        r"(?m)^[ \t]*\d{1,3}[ \t]+Mode D only"]:
                if re.search(pat, txt):
                    leaks.append(pat)
            if leaks:
                fail("no page-number leakage in extracted manuscript text", f"{leaks}")
            else:
                ok("no page-number leakage patterns in extracted PDF text")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            print("  [skip] pdftotext unavailable; page-leakage check skipped")
    else:
        print("  [skip] PDF not present; page-leakage check skipped")

    # ---- 7. unprofessional wording + bullet artifacts ----
    unprof = re.findall(r"serious\s+(?:1d|2d|spatial|spatial refinement)", tex, re.I)
    # stray non-ASCII bullet artifacts (the '\uf0b7'-class glyphs from PDF extraction)
    artifacts = [c for c in tex if ord(c) >= 0xF000]
    if unprof:
        fail("no unprofessional wording ('serious 1D/2D')", f"{unprof[:3]}")
    elif artifacts:
        fail("no bullet/glyph artifacts", f"{len(artifacts)} private-use glyphs")
    else:
        ok("no unprofessional wording or bullet/glyph artifacts")

    print("\n" + "=" * 70)
    if FAILURES:
        print(f"RESULT: FAIL ({len(FAILURES)} checks failed)")
        return 1
    print("RESULT: PASS (manuscript consistent with canonical outputs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
