"""Every file in the repository has exactly one disposition, and it is ruled.

The convergence directive requires each tracked file to receive one of eight
dispositions with no miscellaneous bucket. That is only true on the day a
CSV is written unless something checks it on every commit afterwards, so
FILE_DISPOSITION.csv is generated by tools/file_disposition.py and this
holds the committed file to what the rules produce for the tree as it is.
"""
from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import file_disposition as fd  # noqa: E402

VOCABULARY = {"KEEP_AS_IS", "KEEP_AND_HARDEN", "EXTRACT_GENERIC",
              "KEEP_AS_MODEL_PLUGIN", "REWRITE_GENERIC", "REGENERATE",
              "RETIRE_TO_HISTORY", "DELETE_GENERATED_AND_REBUILD"}


def _committed_rows():
    text = (ROOT / "FILE_DISPOSITION.csv").read_text(encoding="utf-8")
    return list(csv.DictReader(io.StringIO(text)))


def test_the_committed_table_is_what_the_rules_produce():
    text, unmatched, unused = fd.generate()
    assert not unmatched, f"files no rule disposes of: {unmatched}"
    assert not unused, f"rules that match no file: {unused}"
    assert (ROOT / "FILE_DISPOSITION.csv").read_text(
        encoding="utf-8") == text, (
        "FILE_DISPOSITION.csv is stale; run "
        "`python tools/file_disposition.py --write`")


def test_every_repository_file_has_exactly_one_row():
    rows = _committed_rows()
    paths = [r["path"] for r in rows]
    assert len(paths) == len(set(paths)), "a file has two dispositions"
    assert set(paths) == set(fd.repository_files())


def test_every_row_uses_the_vocabulary_and_says_why():
    for r in _committed_rows():
        assert r["disposition"] in VOCABULARY, r
        assert r["rationale"].strip(), f"{r['path']}: no rationale"


def test_the_whole_vocabulary_is_in_use():
    """Eight dispositions were asked for; a table using fewer has quietly
    merged two of them."""
    used = {r["disposition"] for r in _committed_rows()}
    assert used == VOCABULARY, sorted(VOCABULARY - used)


def test_a_file_no_rule_names_is_refused():
    """ANTI-VACUITY: there is no catch-all rule to absorb a new file."""
    _, unmatched, _ = fd.generate(files=["a_new_file_nobody_ruled_on.xyz"])
    assert unmatched == ["a_new_file_nobody_ruled_on.xyz"]


@pytest.mark.parametrize("path,expected", [
    ("qta_multiphysics/machine_fsm.py", "RETIRE_TO_HISTORY"),
    ("qta_multiphysics/thermal_1d.py", "KEEP_AS_MODEL_PLUGIN"),
    ("qta_multiphysics/grids.py", "EXTRACT_GENERIC"),
    ("qta_agent/events.py", "KEEP_AND_HARDEN"),
    ("thermal_3d_hotspots.csv", "DELETE_GENERATED_AND_REBUILD"),
    ("results_gate_table.csv", "RETIRE_TO_HISTORY"),
    ("final_manifest.json", "REGENERATE"),
])
def test_first_match_wins_where_it_matters(path, expected):
    """A specific file must precede its directory's rule; these are the
    places an ordering slip would move a file into the wrong phase."""
    r = fd.rule_for(path, fd._regen_set())
    assert r is not None and r[0] == expected, (path, r)
