"""Read-only retrieval index over the project's own governed documents.

MODEL-ONLY / FORECAST-ONLY / PRE-EXPERIMENTAL. Zero PASS. No measured data.

"Read-only RAG" here means exactly what it says, and the constraints are the
point of the module:

* **Retrieval only — no generation.** This module returns verbatim spans of
  governed documents with citations. It never paraphrases, never summarises,
  and never calls a language model. The "G" in RAG is a human reading the
  cited span.
* **Read-only over the corpus.** The corpus is opened for reading and nothing
  else. The only thing written is a serialized index, and only into the
  guarded Stage-10 workspace.
* **Offline and deterministic.** Pure standard library: an Okapi BM25 index
  built in-process. No network client is imported, no embedding service is
  called, no model weights are loaded, and the same corpus always yields the
  same index bytes and the same ranking.
* **Provenance on every hit.** Each result carries the source path, the line
  range, and the SHA-256 of the source file at index time, so a retrieved
  claim can always be walked back to the governed document that made it — and
  a stale index is detectable rather than silently wrong.
* **Retrieved text is not evidence.** Everything in this corpus is
  forecast-only; retrieving a sentence about a threshold does not make the
  threshold measured. ``automatic_gate_effect = NONE``.

The corpus is the project's Markdown documentation plus its plain-text audit
files. Non-governed trees (``attic/``), binaries, and generated workspaces are
excluded by construction.
"""
from __future__ import annotations

import hashlib
import math
import re
from collections import Counter
from collections.abc import Iterable, Sequence
from pathlib import Path, PurePosixPath

from . import AUTOMATIC_GATE_EFFECT, LABEL
from .workspace import (StrPath, guard_output_dir, repo_root, sha256_file,
                        write_json_deterministic)

INDEX_SCHEMA_VERSION = "1.0.0"
BM25_K1 = 1.5
BM25_B = 0.75
MAX_SNIPPET_CHARS = 600

# Non-governed or generated trees are never indexed.
EXCLUDED_DIRS = ("attic", "verification", ".git", ".venv", "outputs",
                 "release", "__pycache__")
CORPUS_GLOBS = ("*.md", "*.txt")

#: Files the globs catch that are not governed DOCUMENTS, and why.
#:
#: The corpus exists so a reader can be handed a verbatim span of something
#: somebody wrote. Two kinds of file match ``*.txt`` and satisfy neither half
#: of that: a derived digest, whose content is regenerated by a build step
#: and whose "verbatim span" is sixty-four hex characters; and a git bundle,
#: which is binary pack data wearing a text extension.
#:
#: Excluded by name rather than by heuristic. A rule that guessed -- "looks
#: like a hash", "mostly non-printable" -- would drop a real document the
#: day somebody wrote one that fit, and the failure would be silent.
EXCLUDED_FILES = {
    "manifest_hash.txt": "a derived digest of final_manifest.json, "
                         "regenerated by generate_manifest.py",
    "deep_dataset_hash.txt": "a derived digest of the deep dataset",
    "QTA_full_history-6.bundle.txt": "a git bundle: binary pack data with a "
                                     "text extension, and 1.4 MB of it",
}
#: The committed record of what the corpus IS. See :func:`load_allowlist`.
CORPUS_ALLOWLIST = "docs/corpus_allowlist.json"
ALLOWLIST_SCHEMA_VERSION = 1
CORPUS_SUFFIXES = tuple(g.lstrip("*") for g in CORPUS_GLOBS)

#: Upper bound on results per query. Retrieval hands verbatim spans to a
#: reader; an unbounded k turns "retrieve" into "dump the corpus", which is a
#: different operation with different review implications.
MAX_K = 50

STOPWORDS = frozenset("""
a an and are as at be by for from has have in into is it its of on or
that the their then there these this to was were which with without not no
""".split())

_TOKEN = re.compile(r"[a-z0-9_]+")


def tokenize(text: str) -> list[str]:
    """Lowercase alphanumeric tokens, stopwords dropped, no stemming.

    Deliberately boring: a deterministic tokenizer keeps the index bytes and
    the ranking reproducible, which matters more here than recall.
    """
    return [t for t in _TOKEN.findall(text.lower())
            if len(t) > 1 and t not in STOPWORDS]


def corpus_files(root: StrPath | None = None) -> list[str]:
    """Governed text documents, as repo-relative POSIX paths, sorted."""
    root = Path(root) if root is not None else repo_root()
    out = []
    for pattern in CORPUS_GLOBS:
        for p in root.rglob(pattern):
            rel = p.relative_to(root)
            if any(part in EXCLUDED_DIRS for part in rel.parts):
                continue
            if rel.as_posix() in EXCLUDED_FILES:
                continue
            if not p.is_file():
                continue
            out.append(rel.as_posix())
    return sorted(set(out))


class CorpusMembershipError(ValueError):
    """The corpus on disk is not the corpus that was reviewed."""


def load_allowlist(root: StrPath | None = None) -> dict:
    """The committed ``{path: sha256}`` the corpus is checked against.

    WHY MEMBERSHIP NEEDED A RECORD

    Membership used to be "whatever ``*.md`` the walk found outside the
    excluded trees". Every guard in :func:`_validate_corpus_paths` protected
    the SHAPE of a path and none of them protected the SET: dropping a file
    into the tree made it governed text a reader would be handed with this
    module's provenance on it, and nothing anywhere had to approve that.

    So the corpus is now declared. Adding a document is an edit to a
    committed file, visible in review, rather than a side effect of creating
    one.

    WHAT "ATTESTED" MEANS HERE, AND WHAT IT DOES NOT

    Each entry carries the file's content digest, and the allowlist carries a
    digest of its own entries -- so a silent edit to either the corpus or the
    list is detectable. It is NOT cryptographically signed: there is no key
    authority in this repository, so nothing here can establish WHO approved
    the list, only that what is on disk is what the list describes. The
    review that put it in the commit is the authority; this is the mechanism
    that makes divergence from it visible.

    Fails closed on absence. A missing allowlist is not an empty one: an
    empty allowlist would refuse every document, and a MISSING one read as
    empty would be the vacuous-success shape -- a membership check that
    passes because it examined nothing.
    """
    import json
    root = Path(root) if root is not None else repo_root()
    path = root / CORPUS_ALLOWLIST
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise CorpusMembershipError(
            f"no corpus allowlist at {CORPUS_ALLOWLIST} ({exc}). Retrieval "
            "refuses rather than falling back to 'whatever is on disk': that "
            "fallback is the state this file exists to end") from None
    try:
        doc = json.loads(raw)
    except ValueError as exc:
        raise CorpusMembershipError(
            f"corpus allowlist is unparseable: {exc}") from None
    if not isinstance(doc, dict):
        raise CorpusMembershipError(
            f"corpus allowlist is {type(doc).__name__}, not an object")
    if doc.get("schema_version") != ALLOWLIST_SCHEMA_VERSION:
        raise CorpusMembershipError(
            f"corpus allowlist schema {doc.get('schema_version')!r} != "
            f"{ALLOWLIST_SCHEMA_VERSION!r}")
    entries = doc.get("entries")
    if not isinstance(entries, list) or not entries:
        raise CorpusMembershipError(
            "corpus allowlist has no entries. An allowlist that names nothing "
            "would make every membership check pass by examining nothing")
    out: dict = {}
    for e in entries:
        if not isinstance(e, dict):
            raise CorpusMembershipError(
                f"allowlist entry is {type(e).__name__}, not an object")
        rel, sha = e.get("path"), e.get("sha256")
        if not isinstance(rel, str) or not rel:
            raise CorpusMembershipError(f"allowlist entry names no path: {e!r}")
        if not isinstance(sha, str) or len(sha) != 64:
            raise CorpusMembershipError(
                f"allowlist entry {rel!r} carries no sha256 digest")
        if rel in out:
            raise CorpusMembershipError(
                f"allowlist names {rel!r} twice; two entries for one path "
                "cannot both be the one that was reviewed")
        out[rel] = sha
    claimed = doc.get("entries_digest")
    actual = hashlib.sha256(
        "\n".join(f"{k} {out[k]}" for k in sorted(out)).encode("utf-8")
    ).hexdigest()
    if claimed != actual:
        raise CorpusMembershipError(
            f"corpus allowlist claims entries_digest {str(claimed)[:12]} and "
            f"its entries hash to {actual[:12]}; the list was edited without "
            "being regenerated, and which half is right is not this module's "
            "guess to make")
    return out


def allowlist_document(root: StrPath | None = None) -> dict:
    """The allowlist the corpus on disk WOULD produce. Returns; never writes.

    Deliberately returns rather than writing. A library function that could
    write the allowlist would let production code approve its own corpus,
    which is the property this whole mechanism exists to hold; writing is
    ``tools/corpus_allowlist.py --write``, and its output lands in a commit.
    """
    root = Path(root) if root is not None else repo_root()
    rels = corpus_files(root)
    entries = [{"path": rel,
                "sha256": hashlib.sha256((root / rel).read_bytes()).hexdigest()}
               for rel in rels]
    return {
        "schema_version": ALLOWLIST_SCHEMA_VERSION,
        "label": "corpus membership for read-only retrieval",
        "note": ("A document is retrievable because it appears here, not "
                 "because it exists. Regenerate with "
                 "tools/corpus_allowlist.py --write in the same commit that "
                 "adds or edits the document, so the change is reviewed "
                 "rather than absorbed. Content-addressed, not signed: this "
                 "repository has no key authority, so the list attests what "
                 "the corpus IS and cannot attest who approved it."),
        "entries_digest": hashlib.sha256(
            "\n".join(f"{e['path']} {e['sha256']}" for e in entries)
            .encode("utf-8")).hexdigest(),
        "entries": entries,
    }


def assert_corpus_is_allowlisted(root: StrPath | None = None,
                                 rels: Sequence[str] | None = None) -> dict:
    """The corpus on disk must BE the corpus that was reviewed.

    Both directions, and both matter for different reasons:

    * a file on disk that the list does not name is undeclared governed text,
      which is the whole attack -- write a document, have it quoted back with
      provenance nobody granted;
    * a file the list names that is not on disk (or whose bytes changed) means
      the reviewed corpus no longer exists, and continuing would retrieve from
      something other than what was approved.

    Returns the verified ``{path: sha256}`` mapping.
    """
    root = Path(root) if root is not None else repo_root()
    allowed = load_allowlist(root)
    found = list(rels) if rels is not None else corpus_files(root)
    undeclared = sorted(set(found) - set(allowed))
    if undeclared:
        raise CorpusMembershipError(
            f"{len(undeclared)} document(s) are in the corpus tree and not in "
            f"{CORPUS_ALLOWLIST}: {undeclared[:5]}. A file becomes governed "
            "text by being reviewed into the allowlist, not by being created")
    missing = sorted(set(allowed) - set(found))
    if missing:
        raise CorpusMembershipError(
            f"{len(missing)} allowlisted document(s) are not in the corpus: "
            f"{missing[:5]}. The reviewed corpus no longer exists, so what "
            "retrieval would return is not what was approved")
    changed = []
    for rel in sorted(found):
        raw = (root / rel).read_bytes()
        if hashlib.sha256(raw).hexdigest() != allowed[rel]:
            changed.append(rel)
    if changed:
        raise CorpusMembershipError(
            f"{len(changed)} allowlisted document(s) no longer hash to what "
            f"the allowlist records: {changed[:5]}. Regenerate the allowlist "
            "in the commit that changes the document, so the change is "
            "reviewed rather than absorbed")
    return allowed


def _validate_corpus_paths(root: Path, rels: list) -> list:
    """Validate caller-supplied corpus paths. Fail closed on every doubt.

    ``build_index(paths=[...])`` lets a caller name the corpus explicitly, and
    that argument is the retrieval layer's whole attack surface: whatever is
    named here becomes text a reader may act on, carrying this module's
    provenance. So the names are checked, not trusted.

    Retrieval stays read-only either way -- nothing here writes -- but
    read-only is not the same as harmless. A path that escapes the corpus root
    turns an index of governed documents into a way to read ``.git/config``
    and hand it back wearing a governed label.
    """
    seen: dict = {}
    out: list = []
    for rel in rels:
        if not isinstance(rel, str) or not rel:
            raise ValueError(f"corpus path must be a non-empty string: {rel!r}")
        if PurePosixPath(rel).is_absolute() or Path(rel).is_absolute():
            raise ValueError(
                f"unsafe corpus path {rel!r}: absolute paths are refused so "
                "the corpus root is the only thing that decides what is in it")
        parts = PurePosixPath(rel).parts
        if any(part in ("..", ".") for part in parts):
            raise ValueError(
                f"unsafe corpus path {rel!r}: '..' and '.' segments are "
                "refused rather than normalised")
        if any(part in EXCLUDED_DIRS for part in parts):
            raise ValueError(
                f"corpus path {rel!r} lies under an excluded directory; these "
                "trees are generated, untracked or non-governed and are "
                "excluded from retrieval by policy")
        if rel in EXCLUDED_FILES:
            raise ValueError(
                f"corpus path {rel!r} is excluded from retrieval: "
                f"{EXCLUDED_FILES[rel]}. Naming it explicitly does not make "
                "it a governed document")
        if not rel.endswith(CORPUS_SUFFIXES):
            raise ValueError(
                f"corpus path {rel!r} is not a governed text document "
                f"{CORPUS_SUFFIXES}")

        p = root / rel
        try:
            resolved = p.resolve()
        except OSError as exc:
            raise ValueError(f"corpus path {rel!r} is unreadable: {exc}") from exc
        if p.is_symlink():
            raise ValueError(
                f"corpus path {rel!r} is a symlink; its target is chosen by "
                "whoever can write the directory, not by the corpus root")
        root_resolved = root.resolve()
        if resolved != root_resolved and root_resolved not in resolved.parents:
            raise ValueError(
                f"unsafe corpus path {rel!r}: resolves outside the corpus root")
        if not p.is_file():
            raise ValueError(f"corpus path {rel!r} is not a regular file")
        if resolved in seen:
            raise ValueError(
                f"duplicate corpus entry: {rel!r} and {seen[resolved]!r} name "
                "the same file, which would double its weight in the ranking")
        seen[resolved] = rel
        out.append(rel)
    return out


def split_chunks(text: str, path: str) -> list[dict]:
    """Split a document into heading-anchored chunks with 1-based line ranges.

    Markdown headings start a new chunk; blank-line-separated blocks inside a
    section are grouped up to a size bound. Chunks keep their line range so a
    hit cites ``file:start-end`` and a reader can open exactly that span.
    """
    lines = text.splitlines()
    chunks: list[dict] = []
    buf: list[str] = []
    start, heading = 1, ""

    def flush(end_line: int) -> None:
        body = "\n".join(buf).strip()
        if body:
            chunks.append({"path": path, "line_start": start,
                           "line_end": end_line, "heading": heading,
                           "text": body})

    for i, line in enumerate(lines, 1):
        is_heading = line.startswith("#")
        too_long = sum(len(b) for b in buf) > MAX_SNIPPET_CHARS * 2
        if (is_heading or too_long) and buf:
            flush(i - 1)
            buf, start = [], i
        if is_heading:
            heading = line.lstrip("#").strip()
        buf.append(line)
    flush(len(lines) if lines else 1)
    return chunks


class ReadOnlyIndex:
    """In-memory BM25 index. Construction reads; nothing here ever writes."""

    def __init__(self, chunks: Iterable[dict], file_digests: dict,
                 root: StrPath | None = None) -> None:
        self.root = Path(root) if root is not None else repo_root()
        self.chunks = list(chunks)
        self.file_digests = dict(file_digests)
        self.doc_tokens = [tokenize(c["text"]) for c in self.chunks]
        self.doc_len = [len(t) for t in self.doc_tokens]
        self.n_docs = len(self.chunks)
        self.avg_len = (sum(self.doc_len) / self.n_docs) if self.n_docs else 0.0
        self.term_freq = [Counter(t) for t in self.doc_tokens]
        df: Counter = Counter()
        for tf in self.term_freq:
            df.update(tf.keys())
        self.doc_freq: dict[str, int] = dict(df)

    # ---- scoring ----
    def idf(self, term: str) -> float:
        n_q = self.doc_freq.get(term, 0)
        if n_q == 0:
            return 0.0
        return math.log(1.0 + (self.n_docs - n_q + 0.5) / (n_q + 0.5))

    def score(self, query_terms: Sequence[str], doc_id: int) -> float:
        tf, dl = self.term_freq[doc_id], self.doc_len[doc_id]
        s = 0.0
        for term in query_terms:
            f = tf.get(term, 0)
            if not f:
                continue
            denom = f + BM25_K1 * (1 - BM25_B + BM25_B * dl /
                                   (self.avg_len or 1.0))
            s += self.idf(term) * f * (BM25_K1 + 1) / denom
        return s

    def search(self, query: str, k: int = 5, path_prefix: str | None = None
               ) -> list[dict]:
        """Top-``k`` verbatim spans for ``query``, each with full provenance.

        Ties break on document id so the ranking is stable; scores of zero are
        dropped rather than padded, because an empty result is a truthful
        answer and a padded one is not.
        """
        if isinstance(k, bool) or not isinstance(k, int):
            raise ValueError(
                f"k must be an int, got {type(k).__name__}; bools and strings "
                "are refused rather than coerced, because a silently coerced "
                "k changes how much of the corpus a reader is handed")
        if not 1 <= k <= MAX_K:
            raise ValueError(f"k must be between 1 and {MAX_K}, got {k}")
        terms = tokenize(query)
        if not terms:
            return []
        scored: list[tuple[float, int]] = []
        for doc_id, chunk in enumerate(self.chunks):
            if path_prefix and not chunk["path"].startswith(path_prefix):
                continue
            s = self.score(terms, doc_id)
            if s > 0.0:
                scored.append((-s, doc_id))
        scored.sort()
        hits: list[dict] = []
        for neg_s, doc_id in scored[:int(k)]:
            c = self.chunks[doc_id]
            snippet = c["text"]
            truncated = len(snippet) > MAX_SNIPPET_CHARS
            hits.append({
                "rank": len(hits) + 1,
                "score": round(-neg_s, 9),
                "path": c["path"],
                "line_start": c["line_start"], "line_end": c["line_end"],
                "citation": f"{c['path']}:{c['line_start']}-{c['line_end']}",
                "heading": c["heading"],
                "source_sha256": self.file_digests.get(c["path"], ""),
                "text": snippet[:MAX_SNIPPET_CHARS],
                "truncated": truncated,
                "label": LABEL,
                "evidence_status": "RETRIEVED_TEXT_NOT_EVIDENCE",
            })
        return hits

    def stale_files(self) -> list[str]:
        """Corpus files whose bytes changed since the index was built."""
        bad: list[str] = []
        for rel, digest in sorted(self.file_digests.items()):
            p = self.root / rel
            if not p.exists() or sha256_file(p) != digest:
                bad.append(rel)
        return bad

    def to_dict(self) -> dict:
        return {
            "schema_version": INDEX_SCHEMA_VERSION,
            "label": LABEL,
            "automatic_gate_effect": AUTOMATIC_GATE_EFFECT,
            "producer": "qta_multiphysics.stack.rag_index",
            "retrieval": {"model": "Okapi BM25", "k1": BM25_K1, "b": BM25_B,
                          "tokenizer": "lowercase [a-z0-9_]+, stopwords "
                                       "dropped, no stemming"},
            "generation": "NONE — retrieval returns verbatim cited spans; no "
                          "language model is called and no text is synthesised",
            "network_access": "NONE — index and query run entirely offline",
            "write_access": "NONE over the corpus; the index itself is written "
                            "only into the Stage-10 workspace",
            "n_files": len(self.file_digests),
            "n_chunks": self.n_docs,
            "file_digests": dict(sorted(self.file_digests.items())),
            "chunks": [{"path": c["path"], "line_start": c["line_start"],
                        "line_end": c["line_end"], "heading": c["heading"],
                        "text": c["text"]} for c in self.chunks],
        }


def build_index(root: StrPath | None = None,
                paths: Iterable[str] | None = None) -> ReadOnlyIndex:
    """Build the index by reading the governed corpus (no writes at all)."""
    root = Path(root) if root is not None else repo_root()
    if paths is not None:
        rels = _validate_corpus_paths(root, list(paths))
    else:
        rels = corpus_files(root)
    # MEMBERSHIP, checked here rather than at every call site.
    #
    # The shape guards above decide whether a path is safe to read. This
    # decides whether the document was ever meant to be retrievable, which is
    # a different question and the one nothing was asking: a file dropped
    # into the tree passed every shape check and became governed text.
    #
    # Checked against the FULL corpus, not against `rels`. A caller naming a
    # subset is narrowing what it indexes, and a caller naming a subset must
    # not thereby skip the question of whether the tree contains something
    # undeclared -- that would make the check optional by argument, which is
    # the opt-in weakness this repository already carries once.
    assert_corpus_is_allowlisted(root)
    chunks: list[dict] = []
    digests: dict[str, str] = {}
    for rel in rels:
        p = root / rel
        raw = p.read_bytes()
        digests[rel] = hashlib.sha256(raw).hexdigest()
        chunks.extend(split_chunks(raw.decode("utf-8", errors="replace"), rel))
    return ReadOnlyIndex(chunks, digests, root=root)


def load_index(path: StrPath,
               root: StrPath | None = None) -> ReadOnlyIndex:
    """Rebuild an index from source and require the stored document to match.

    A serialized index is a CACHE, never an authority. It carries verbatim
    text, line ranges and source paths that a reader will treat as quotations
    from governed documents -- so if the file on disk were trusted, anyone who
    could write it could put words into a governed document's mouth: change a
    chunk's text to "gate PASS", or repoint its path at a file the corpus
    never contained, and the provenance fields would still look impeccable.

    The check is therefore not a checksum over the document (which whoever
    rewrote it could also recompute) but a rebuild from the source files it
    names, compared field for field. Anything the document asserts that the
    corpus does not produce is a mismatch: label, digests, text, line ranges,
    paths, retrieval parameters, all of it.

    A mismatch is reported as "stale or forged" because from here those are
    genuinely indistinguishable -- the source may have moved on, or the index
    may have been rewritten -- and naming only one of them would be a guess
    presented as a diagnosis. Either way the answer is the same: rebuild.
    """
    import json
    raw = Path(path).read_text()
    try:
        doc = json.loads(raw)
    except ValueError as exc:
        raise ValueError(
            f"index document is unparseable ({type(exc).__name__})") from exc
    if not isinstance(doc, dict):
        raise ValueError(
            f"index document is {type(doc).__name__}, not an object")
    if doc.get("schema_version") != INDEX_SCHEMA_VERSION:
        raise ValueError(
            f"index schema {doc.get('schema_version')!r} != "
            f"{INDEX_SCHEMA_VERSION!r}; rebuild the index")

    stored_digests = doc.get("file_digests")
    if not isinstance(stored_digests, dict) or not all(
            isinstance(k, str) and isinstance(v, str)
            for k, v in stored_digests.items()):
        raise ValueError("index file_digests must map path -> sha256 digest")

    index_root = Path(root) if root is not None else repo_root()
    rebuilt = build_index(root=index_root,
                          paths=_validate_corpus_paths(
                              index_root, sorted(stored_digests)))
    expected = rebuilt.to_dict()
    if expected != doc:
        differing = sorted(
            key for key in set(expected) | set(doc)
            if expected.get(key) != doc.get(key))
        raise ValueError(
            f"index is stale or forged: rebuilding from source disagrees on "
            f"{differing}. A serialized index is a cache of the corpus, not a "
            "second copy of it with independent standing; rebuild it.")
    return rebuilt


def write_index(out_dir: StrPath, root: StrPath | None = None,
                paths: Iterable[str] | None = None) -> dict:
    """Persist a deterministic index document into the guarded workspace."""
    out = guard_output_dir(out_dir)
    index = build_index(root=root, paths=paths)
    doc = index.to_dict()
    digest = write_json_deterministic(out / "rag_index.json", doc)
    return {"label": LABEL, "automatic_gate_effect": AUTOMATIC_GATE_EFFECT,
            "index_file": "rag_index.json", "sha256": digest,
            "n_files": doc["n_files"], "n_chunks": doc["n_chunks"],
            "schema_version": INDEX_SCHEMA_VERSION}


def retrieve(query: str, k: int = 5, root: StrPath | None = None,
             path_prefix: str | None = None) -> dict:
    """One-shot retrieval: build, query, and report — with the boundary stated.

    The returned document is deliberately shaped so it cannot be mistaken for
    an answer: it contains the query, the cited spans, and an explicit
    statement that retrieved text is not evidence and no generation occurred.
    """
    index = build_index(root=root)
    hits = index.search(query, k=k, path_prefix=path_prefix)
    return {
        "label": LABEL,
        "automatic_gate_effect": AUTOMATIC_GATE_EFFECT,
        "query": query,
        "n_hits": len(hits),
        "hits": hits,
        "corpus": {"n_files": len(index.file_digests),
                   "n_chunks": index.n_docs},
        "generation": "NONE",
        "disclaimer": "verbatim spans of forecast-only documents; retrieving "
                      "a statement does not make it measured, validated, or "
                      "gate evidence",
    }
