"""Deterministic shards for the mutation matrices, and the runner for one.

WHY. The agent-substrate job ran every matrix serially in one job: 4h27m of
it at d633c77 (hosted run 36094744039), on a runner that GitHub stops at six
hours, and a runner lost at hour four took every result with it. Sharding
must not buy that time back with coverage, so what holds is stated here and
checked, not assumed:

* **Every spec, every cycle.** ``plan()`` puts every ``tools/mutations/*.json``
  in exactly one shard. There is no sampling and no rotation.
* **Deterministic.** Longest-processing-time on the committed WEIGHTS (the
  measured seconds of each spec's step in that run), ties broken by name; a
  spec not yet measured is weighed at its mutation count times the median
  measured seconds per mutation. Same specs, same shards, on every machine.
* **The workflow's matrix is generated, not typed.** ``--emit`` prints the
  ``include:`` block; ``--check`` fails unless the block between the markers
  in agent-substrate.yml is exactly that, and unless the shard job, the
  aggregate job and its success test are all present in the shape that makes
  "overall green" mean "every shard passed". A spec left out of the block, a
  shard deleted, or ``fail-fast`` turned back on is a contract failure.
* **Each shard keeps every per-spec guarantee**, because each spec still runs
  through ``tools/mutation_matrix.py`` unchanged: baseline, null control,
  non-zero exit on a survivor, an anchor that does not match once, a timeout
  or a source not restored byte-identical. ``--run`` runs every spec it is
  given even after one fails, so one red spec does not hide another, and
  fails if the tracked tree differs afterwards -- git as the independent
  check of the harness's own re-hashing.
* **A lost runner is never a pass.** The aggregate job runs ``if: always()``
  and requires the shard job's result to be ``success``; a cancelled,
  skipped or timed-out shard is not success. Nothing here reads a shard's
  output to infer what it killed, so nothing can mistake silence for a kill.
"""
from __future__ import annotations

import argparse
import json
import re
import statistics
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MUTATIONS = ROOT / "tools" / "mutations"
WORKFLOW = ROOT / ".github" / "workflows" / "agent-substrate.yml"
SHARDS = 8

BEGIN = "          # BEGIN generated by tools/mutation_shards.py --emit"
END = "          # END generated by tools/mutation_shards.py --emit"

#: Seconds each spec's step took in hosted run 36094744039 (d633c77, the
#: last serial run). A weight, not a budget: it decides placement only.
WEIGHTS = {
    "agent_actions.json": 305, "agent_agents.json": 267,
    "agent_audit.json": 614, "agent_checkpoint.json": 175,
    "agent_compensation.json": 143, "agent_cross_process.json": 229,
    "agent_delegation.json": 48, "agent_evidence.json": 156,
    "agent_execution.json": 733, "agent_fault_injection.json": 41,
    "agent_idempotency.json": 494, "agent_incremental.json": 25,
    "agent_job_graph.json": 715, "agent_lease_renewal.json": 165,
    "agent_memory_context.json": 89, "agent_netauth.json": 136,
    "agent_policy.json": 57, "agent_readpath.json": 377,
    "agent_recovery.json": 396, "agent_scheduler.json": 429,
    "agent_second_reader.json": 2125, "agent_secret_provider.json": 32,
    "agent_secrets.json": 57, "agent_separate_verify.json": 50,
    "agent_service_authority.json": 214,
    "agent_snapshot_coherence.json": 54, "agent_substrate.json": 987,
    "agent_tasks.json": 1691, "canonical_output_set.json": 47,
    "completion_matrix.json": 31, "corpus_allowlist.json": 41,
    "cross_environment.json": 83, "enforcement_asserts.json": 47,
    "fuzz_harness.json": 242, "governed_breadth.json": 458,
    "hardware_governance.json": 75, "identity_inventory.json": 58,
    "model_check.json": 26, "mutation_harness.json": 1045,
    "output_resolution.json": 74, "repo_contract.json": 61,
    "resolution_inventory.json": 14, "solver_failclosed.json": 1417,
    "stage10_authority.json": 770, "test_isolation.json": 42,
    "unit_inventory.json": 26,
}


def specs() -> list:
    return sorted(p.name for p in MUTATIONS.glob("*.json"))


def _mutations(name: str) -> int:
    return len(json.loads((MUTATIONS / name).read_text(
        encoding="utf-8"))["mutations"])


def weights(names: list) -> dict:
    per = [WEIGHTS[n] / max(_mutations(n), 1) for n in names if n in WEIGHTS]
    rate = statistics.median(per) if per else 1.0
    return {n: WEIGHTS.get(n, _mutations(n) * rate) for n in names}


def plan(names: list | None = None, n: int = SHARDS) -> list:
    """``n`` lists of spec names; each spec in exactly one."""
    names = specs() if names is None else sorted(names)
    w = weights(names)
    shards = [[] for _ in range(n)]
    load = [0.0] * n
    for name in sorted(names, key=lambda s: (-w[s], s)):
        i = min(range(n), key=lambda k: (load[k], k))
        shards[i].append(name)
        load[i] += w[name]
    return [sorted(s) for s in shards]


def emit(shards: list | None = None) -> str:
    shards = plan() if shards is None else shards
    lines = [BEGIN]
    for i, s in enumerate(shards, 1):
        lines.append(f"          - shard: {i}")
        lines.append("            specs: >-")
        lines += [f"              tools/mutations/{name}" for name in s]
    lines.append(END)
    return "\n".join(lines)


def _job(text: str, name: str) -> str | None:
    m = re.search(rf"^  {re.escape(name)}:\s*\n(.*?)(?=^  [A-Za-z0-9_-]+:\s*$"
                  r"|\Z)", text, re.MULTILINE | re.DOTALL)
    return m.group(1) if m else None


def check_workflow(text: str | None = None) -> list:
    """Every way the workflow could run fewer specs than the plan, or report
    green without every shard passing."""
    text = WORKFLOW.read_text(encoding="utf-8") if text is None else text
    out = []
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        out.append("the generated shard block is missing or duplicated")
    else:
        block = text[text.index(BEGIN):text.index(END) + len(END)]
        if block != emit():
            out.append("the shard matrix is not what tools/mutation_shards.py "
                       "--emit generates for the specs on disk; regenerate it")
    shard = _job(text, "mutation-shards")
    if shard is None:
        out.append("no mutation-shards job")
    else:
        if BEGIN not in shard:
            out.append("the generated block is not the mutation-shards matrix")
        if not re.search(r"^\s+fail-fast:\s*false\s*$", shard, re.MULTILINE):
            out.append("mutation-shards must set fail-fast: false, or one red "
                       "shard cancels the others and their verdicts are lost")
        if "tools/mutation_shards.py --run ${{ matrix.specs }}" not in shard:
            out.append("mutation-shards does not run its shard's specs")
    agg = _job(text, "mutation-matrices")
    if agg is None:
        out.append("no mutation-matrices job aggregating the shards")
    else:
        if not re.search(r"^\s+needs:\s*\[?\s*mutation-shards\s*\]?\s*$", agg,
                         re.MULTILINE):
            out.append("mutation-matrices does not wait for mutation-shards")
        if not re.search(r"^\s+if:\s*\$\{\{\s*always\(\)\s*\}\}\s*$|"
                         r"^\s+if:\s*always\(\)\s*$", agg, re.MULTILINE):
            out.append("mutation-matrices must run always(): skipped when a "
                       "shard fails, it would report nothing rather than red")
        if "needs.mutation-shards.result" not in agg or \
                not re.search(r'"success"|\bsuccess\b', agg):
            out.append("mutation-matrices does not require every shard's "
                       "result to be success")
    return out


def _tracked_state() -> str:
    r = subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain",
                        "--untracked-files=no"], capture_output=True,
                       text=True)
    if r.returncode != 0:
        raise SystemExit(f"git status failed: {r.stderr[:200]}")
    diff = subprocess.run(["git", "-C", str(ROOT), "diff", "--binary"],
                          capture_output=True, text=True)
    return r.stdout + diff.stdout


def run(paths: list, runner=None) -> int:
    """Run one shard. Non-zero unless every spec's matrix exits 0 and the
    tracked tree is as it was."""
    names = [Path(p).name for p in paths]
    if not names:
        print("no specs given: an empty shard would pass having run nothing")
        return 1
    if sorted(names) not in plan():
        print(f"{sorted(names)} is not a shard of the committed plan; the "
              "workflow matrix is stale (tools/mutation_shards.py --emit)")
        return 1
    runner = runner or (lambda p: subprocess.run(
        [sys.executable, "tools/mutation_matrix.py", p], cwd=ROOT).returncode)
    before = _tracked_state()
    failed = []
    for p in paths:
        print(f"\n=== {p}", flush=True)
        rc = runner(p)
        if rc != 0:
            failed.append((p, rc))
    changed = _tracked_state() != before
    print("\n=== shard summary")
    for p in paths:
        rc = dict(failed).get(p, 0)
        print(f"  {'ok  ' if rc == 0 else 'FAIL'} {p}"
              + (f" (exit {rc})" if rc else ""))
    if changed:
        print("the tracked tree changed during this shard")
    return 1 if failed or changed else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--emit", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--run", nargs="*", metavar="SPEC")
    args = ap.parse_args(argv)
    if args.emit:
        print(emit())
        return 0
    if args.check:
        problems = check_workflow()
        for p in problems:
            print(p)
        if problems:
            return 1
        w = weights(specs())
        loads = [sum(w[s] for s in sh) / 60 for sh in plan()]
        print(f"{len(specs())} specs in {SHARDS} shards, each exactly once; "
              f"estimated minutes per shard {[round(x) for x in loads]}")
        return 0
    return run(args.run)


if __name__ == "__main__":
    sys.exit(main())
