#!/usr/bin/env python3
"""Where the hardware-era machine semantics still appear, and why (NF-1T s.53).

The former apparatus design had machine modes A/B/C/D, a B -> C -> D
sequence and gas-species routing (methane, helium). None of that is a
concept of the learned-model substrate. This audit finds every occurrence in
the tracked tree and puts each file in exactly one class by an ordered rule
table (first match wins), so an occurrence nobody explained is UNCLASSIFIED
and fails the check rather than disappearing into a bucket.

Classes (directive s.53)

``ACTIVE_NEURAL_SEMANTIC_LEAK``   in the neural substrate, its tools or its
                                  tests -- the check requires ZERO;
``ACTIVE_GENERIC_SEMANTIC_LEAK``  in an ACTIVE generic module (reported);
``LEGACY_COMPATIBILITY``          code or tests kept so legacy artefacts
                                  stay reproducible;
``LEGACY_SCIENTIFIC_HISTORY``     legacy outputs and retired modules;
``DOCUMENTATION_HISTORY``         prose and comments that record history;
``TEST_OF_BOUNDARY``              a test whose job is to keep these terms
                                  out of somewhere;
``TOOLING_CLASSIFIER_REFERENCE``  a tool that classifies, audits or reads
                                  the legacy corpus by these names;
``FALSE_POSITIVE``                a match that is not the hardware concept
                                  (each listed with its reason).

The report records file, class, hit count and line numbers -- never the
matched text, so the report itself carries none of the terms.

    python tools/neural_legacy_audit.py            # print the summary
    python tools/neural_legacy_audit.py --write    # write the report
    python tools/neural_legacy_audit.py --check    # exit 1 unless 0 neural
                                                   # leaks and 0 unclassified
"""
from __future__ import annotations

import argparse
import csv
import fnmatch
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = Path("docs") / "neural" / "legacy_semantic_audit.json"

PATTERNS = {
    "machine_mode_label": re.compile(r"(?i)\bmode[_ ]?[abcd](?:_|\b)"),
    "methane_routing": re.compile(r"(?i)\bmethane\b"),
    "helium_routing": re.compile(r"(?i)\bhelium\b"),
    "mode_sequence": re.compile(r"\bB\s*(?:->|→)\s*C\s*(?:->|→)"
                                r"\s*D\b"),
}
CLASSES = ("ACTIVE_NEURAL_SEMANTIC_LEAK", "ACTIVE_GENERIC_SEMANTIC_LEAK",
           "LEGACY_COMPATIBILITY", "LEGACY_SCIENTIFIC_HISTORY",
           "DOCUMENTATION_HISTORY", "TEST_OF_BOUNDARY",
           "TOOLING_CLASSIFIER_REFERENCE", "FALSE_POSITIVE")
BINARY = (".pdf", ".h5", ".safetensors", ".png", ".jpg", ".zip", ".gz",
          ".npz", ".pyc")

#: (pattern, class, why). Path patterns are fnmatch; first match wins.
PATH_RULES = (
    ("docs/neural/legacy_semantic_audit.json", "TOOLING_CLASSIFIER_REFERENCE",
     "this audit's own report (line numbers only; never scanned for "
     "content)"),
    ("scientific_ai/*", "ACTIVE_NEURAL_SEMANTIC_LEAK",
     "the learned-model substrate"),
    ("tools/neural_legacy_audit.py", "TOOLING_CLASSIFIER_REFERENCE",
     "this audit: its patterns name what it looks for"),
    ("tools/neural*.py", "ACTIVE_NEURAL_SEMANTIC_LEAK",
     "the substrate's tools"),
    ("tests/test_neural_boundary.py", "TEST_OF_BOUNDARY",
     "the test that keeps these semantics out of the substrate"),
    ("tests/test_neural*.py", "ACTIVE_NEURAL_SEMANTIC_LEAK",
     "the substrate's tests"),
    ("docs/neural/*", "ACTIVE_NEURAL_SEMANTIC_LEAK",
     "the substrate's evidence documents"),
    ("FILE_DISPOSITION.csv", "TOOLING_CLASSIFIER_REFERENCE",
     "generated by tools/file_disposition.py: each legacy file's "
     "disposition quotes what it contains"),
    ("tools/framework_boundary.py", "TOOLING_CLASSIFIER_REFERENCE",
     "the active/legacy boundary counts mode labels"),
    ("tools/file_disposition.py", "TOOLING_CLASSIFIER_REFERENCE",
     "classifies every file, legacy ones by what they contain"),
    ("tools/legacy_qta_claims.py", "TOOLING_CLASSIFIER_REFERENCE",
     "enforces the legacy claims boundary, quoting the claims"),
    ("tools/claims_enforcement.py", "TOOLING_CLASSIFIER_REFERENCE",
     "the generic claims boundary, naming what it excludes"),
    ("tools/generic_consistency.py", "TOOLING_CLASSIFIER_REFERENCE",
     "states which legacy concepts the generic check excludes"),
    ("tools/mutations/*", "LEGACY_COMPATIBILITY",
     "mutation specs keeping legacy behaviour under test"),
    ("tools/*.py", "TOOLING_CLASSIFIER_REFERENCE",
     "a tool that reads or audits the legacy corpus by its names"),
    (".github/*", "DOCUMENTATION_HISTORY",
     "workflow comments recording why a step exists"),
    ("tests/test_framework_boundary.py", "TEST_OF_BOUNDARY",
     "the active/legacy boundary test"),
    ("tests/test_claims_boundary.py", "TEST_OF_BOUNDARY",
     "the claims boundary test"),
    ("tests/test_legacy_qta_claims.py", "TEST_OF_BOUNDARY",
     "the legacy claims boundary test"),
    ("tests/test_generic_consistency.py", "TEST_OF_BOUNDARY",
     "asserts the generic check never names legacy concepts"),
    ("tests/*", "LEGACY_COMPATIBILITY",
     "tests that exercise legacy modules and outputs"),
    ("*.md", "DOCUMENTATION_HISTORY", "prose"),
    ("*.tex", "DOCUMENTATION_HISTORY", "the manuscript"),
    ("*.txt", "DOCUMENTATION_HISTORY", "text records"),
    ("docs/*", "DOCUMENTATION_HISTORY", "documentation and records"),
)
#: disposition -> class, after the path rules.
DISPOSITION_RULES = {
    "RETIRE_TO_HISTORY": "LEGACY_SCIENTIFIC_HISTORY",
    "DELETE_GENERATED_AND_REBUILD": "LEGACY_SCIENTIFIC_HISTORY",
    "REGENERATE": "LEGACY_SCIENTIFIC_HISTORY",
    "EXTRACT_GENERIC": "LEGACY_COMPATIBILITY",
    "REWRITE_GENERIC": "LEGACY_COMPATIBILITY",
    "KEEP_AS_IS": "ACTIVE_GENERIC_SEMANTIC_LEAK",
    "KEEP_AND_HARDEN": "ACTIVE_GENERIC_SEMANTIC_LEAK",
    "KEEP_AS_MODEL_PLUGIN": "ACTIVE_GENERIC_SEMANTIC_LEAK",
}
#: path -> why the match is not the hardware concept.
FALSE_POSITIVES: dict = {}


def tracked(root: Path) -> list:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=root,
                         capture_output=True, check=True).stdout
    return sorted(p for p in out.decode().split("\0") if p)


def dispositions(root: Path) -> dict:
    path = root / "FILE_DISPOSITION.csv"
    if not path.exists():
        return {}
    with path.open(newline="", encoding="utf-8") as fh:
        return {r[0]: r[1] for r in csv.reader(fh) if len(r) > 1}


def classify(path: str, disp: dict) -> tuple:
    if path in FALSE_POSITIVES:
        return "FALSE_POSITIVE", FALSE_POSITIVES[path]
    for pat, cls, why in PATH_RULES:
        if fnmatch.fnmatchcase(path, pat):
            return cls, why
    d = disp.get(path)
    if d in DISPOSITION_RULES:
        return DISPOSITION_RULES[d], f"disposition {d}"
    return "UNCLASSIFIED", "no rule covers this file"


def hits(text: str) -> dict:
    out = {}
    for n, line in enumerate(text.splitlines(), 1):
        for name, rx in PATTERNS.items():
            if rx.search(line):
                out.setdefault(name, []).append(n)
    return out


def audit(root: Path = ROOT, files=None) -> dict:
    disp = dispositions(root)
    findings = []
    for path in (files if files is not None else tracked(root)):
        if path.endswith(BINARY) or path == str(OUT):
            continue
        try:
            text = (root / path).read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        h = hits(text)
        if not h:
            continue
        cls, why = classify(path, disp)
        findings.append({"path": path, "class": cls, "why": why,
                         "hits": {k: len(v) for k, v in sorted(h.items())},
                         "lines": {k: v[:20] for k, v in sorted(h.items())}})
    by_class = {c: {"files": 0, "hits": 0} for c in CLASSES + (
        "UNCLASSIFIED",)}
    for f in findings:
        by_class[f["class"]]["files"] += 1
        by_class[f["class"]]["hits"] += sum(f["hits"].values())
    return {
        "schema": "neural-legacy-semantic-audit/1",
        "patterns": {k: v.pattern for k, v in PATTERNS.items()},
        "rules": [{"path": p, "class": c, "why": w}
                  for p, c, w in PATH_RULES],
        "disposition_rules": DISPOSITION_RULES,
        "by_class": by_class,
        "active_neural_semantic_leaks":
            by_class["ACTIVE_NEURAL_SEMANTIC_LEAK"]["files"],
        "unclassified": by_class["UNCLASSIFIED"]["files"],
        "findings": findings,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    rep = audit()
    if args.write:
        (ROOT / OUT).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / OUT).write_text(json.dumps(rep, indent=1, sort_keys=True)
                                + "\n", encoding="utf-8")
    for c, v in rep["by_class"].items():
        if v["files"]:
            print(f"  {c:30s} {v['files']:4d} files {v['hits']:6d} hits")
    ok = rep["active_neural_semantic_leaks"] == 0 and \
        rep["unclassified"] == 0
    print(f"legacy semantic audit: {rep['active_neural_semantic_leaks']} "
          f"neural leak(s), {rep['unclassified']} unclassified -- "
          f"{'PASS' if ok else 'FAIL'}")
    if args.check and (ROOT / OUT).exists():
        committed = json.loads((ROOT / OUT).read_text(encoding="utf-8"))
        if committed != rep:
            print("the committed report is stale: run --write")
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
